# Predição de Churn de Clientes

## Escopo

## Metodologia

## Resultados

# Preparação dos Dados

Importando as blibliotecas

In [53]:
import numpy as np
import pandas as pd
import graphviz
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn import tree

%matplotlib inline

Importando o dataset de churn disponibilizado pela IBM

In [62]:
df = pd.read_csv("telco_churn.csv")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Aqui estou executando a seleção e o tratamento das features para valores aceitáveis pelos modelos:

In [63]:
lbl = preprocessing.LabelEncoder()

for column_name in df.columns:
    if df[column_name].dtype == object:
        df[column_name] = lbl.fit_transform(df[column_name])
    else:
        pass
    
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5373,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,3960,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2563,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,5533,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,6508,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

Realizando o split do dataset em treino e validação.

In [67]:
x_train, x_test, y_train, y_test = train_test_split(df, df["Churn"], test_size = 0.4)


df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5373,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,3960,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2563,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,5533,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,6508,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

# Implementação dos Modelos

## Modelo de Árvore de Decisão

Criando um classificador e rodando a árvores de decisão para todas as features do dataset tendo o Churn como target da classificação

In [71]:
clf = tree.DecisionTreeClassifier(random_state=111, criterion='entropy',max_depth=3,
                                   min_samples_leaf=3)
clf.fit(x_train, y_train)

print(clf.score(x_test, y_test))

print(confusion_matrix(y_test, clf.predict(x_test)))

1.0
[[2054    0]
 [   0  762]]

In [29]:
dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=df.columns,
                         class_names=df["Churn"],
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = graphviz.Source(dot_data)
graph

TypeError: Can't convert 'numpy.int64' object to str implicitly

## Modelo de Regressão Logística